name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Paso opcional: Limpiar la configuración de Git antes del checkout
      - name: Clean git config
        run: git config --global --unset-all http.<url>.extraheader || true

      # Hacer el checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso opcional: Establecer directorio seguro para Git
      - name: Set GIT config directory
        run: git config --global --add safe.directory ${{ github.workspace }}

      # Configurar Node.js para el proyecto
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Instalar dependencias
      - name: Install dependencies
        run: npm install

      # Construir la aplicación
      - name: Build the project
        run: npm run build

      # Desplegar en Azure (este comando depende de cómo estés configurando el despliegue)
      - name: Deploy to Azure
        run: az webapp up --name <nombre-de-tu-app> --resource-group <grupo-de-recursos>
